[project]
name = 'numpy-client'
version = "0.0.0"
description = "A little client for applications driven by numpy"
# Please add authors and correct the email...
authors = [{name='tschm', email= 'tschm@mailinator.com'}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.3",
    "pyarrow>=19.0.0",
]

[project.urls]
repository = "https://github.com/tschm/numpy-client"

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
]

[tool.ruff]
line-length = 120
target-version = "py310"
exclude = [
    "*__init__.py"
]

[tool.ruff.lint]
select = ["E", "F", "I"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/np"]

[tool.hatch.build]
include = [
    "LICENSE",    # Ensure the LICENSE file is included in your package
    "README.md",
    "src/np"
]

[tool.bandit]
exclude_dirs = ["tests"]
